name: Atualização Diária

on:
  schedule:
    - cron: '0 7 * * *' # Roda todo dia às 07:00 UTC (04:00 Brasil)
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar dependências
      run: pip install pandas requests

    - name: Rodar ETL
      run: python etl_divida.py

    - name: Salvar mudanças (Commit)
      run: |
        git config --global user.name 'Bot Monitor Fiscal'
        git config --global user.email 'bot@noreply.github.com'
        git add dados_ranking_estados.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Atualização automática via Siconfi" && git push)